// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package runtime

type ContainerDsnEntry struct {
	NodeletID   string `json:"nodelet_id"`
	ContainerID string `json:"container_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

type McpConnection struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Transport   string `json:"transport"`
	Command     string `json:"command"`
	ArgsJson    string `json:"args_json"`
	EnvJson     string `json:"env_json"`
	Url         string `json:"url"`
	Enabled     int64  `json:"enabled"`
	ContainerID string `json:"container_id"`
	NodeletID   string `json:"nodelet_id"`
}

type Nodelet struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	Token   string `json:"token"`
}

type Project struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	GithubRepo  string `json:"github_repo"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type ProjectExcludedContainer struct {
	ProjectID string `json:"project_id"`
	Ref       string `json:"ref"`
}

type ProjectNodelet struct {
	ProjectID string `json:"project_id"`
	NodeletID string `json:"nodelet_id"`
	Position  int64  `json:"position"`
}

type User struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
