// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package runtime

import (
	"context"
)

const addProjectExclusion = `-- name: AddProjectExclusion :execrows
INSERT INTO project_excluded_containers (project_id, ref)
VALUES (?1, ?2)
ON CONFLICT(project_id, ref) DO NOTHING
`

type AddProjectExclusionParams struct {
	ProjectID string `json:"project_id"`
	Ref       string `json:"ref"`
}

func (q *Queries) AddProjectExclusion(ctx context.Context, arg AddProjectExclusionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addProjectExclusion, arg.ProjectID, arg.Ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addProjectNodelet = `-- name: AddProjectNodelet :execrows
INSERT INTO project_nodelets (project_id, nodelet_id, position)
SELECT
  ?1,
  ?2,
  COALESCE(MAX(position) + 1, 0)
FROM project_nodelets
WHERE project_id = ?1
ON CONFLICT(project_id, nodelet_id) DO NOTHING
`

type AddProjectNodeletParams struct {
	ProjectID string `json:"project_id"`
	NodeletID string `json:"nodelet_id"`
}

func (q *Queries) AddProjectNodelet(ctx context.Context, arg AddProjectNodeletParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addProjectNodelet, arg.ProjectID, arg.NodeletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countDSNEntries = `-- name: CountDSNEntries :one
SELECT COUNT(*) FROM container_dsn_entries
`

func (q *Queries) CountDSNEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDSNEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMCPConnections = `-- name: CountMCPConnections :one
SELECT COUNT(*) FROM mcp_connections
`

func (q *Queries) CountMCPConnections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMCPConnections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodelets = `-- name: CountNodelets :one
SELECT COUNT(*) FROM nodelets
`

func (q *Queries) CountNodelets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodelets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllMCPConnections = `-- name: DeleteAllMCPConnections :exec
DELETE FROM mcp_connections
`

func (q *Queries) DeleteAllMCPConnections(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMCPConnections)
	return err
}

const deleteAllNodelets = `-- name: DeleteAllNodelets :exec
DELETE FROM nodelets
`

func (q *Queries) DeleteAllNodelets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllNodelets)
	return err
}

const deleteDSNEntriesForContainer = `-- name: DeleteDSNEntriesForContainer :exec
DELETE FROM container_dsn_entries
WHERE nodelet_id = ? AND container_id = ?
`

type DeleteDSNEntriesForContainerParams struct {
	NodeletID   string `json:"nodelet_id"`
	ContainerID string `json:"container_id"`
}

func (q *Queries) DeleteDSNEntriesForContainer(ctx context.Context, arg DeleteDSNEntriesForContainerParams) error {
	_, err := q.db.ExecContext(ctx, deleteDSNEntriesForContainer, arg.NodeletID, arg.ContainerID)
	return err
}

const deleteDSNEntry = `-- name: DeleteDSNEntry :exec
DELETE FROM container_dsn_entries
WHERE nodelet_id = ? AND container_id = ? AND key = ?
`

type DeleteDSNEntryParams struct {
	NodeletID   string `json:"nodelet_id"`
	ContainerID string `json:"container_id"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteDSNEntry(ctx context.Context, arg DeleteDSNEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteDSNEntry, arg.NodeletID, arg.ContainerID, arg.Key)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProjectExclusions = `-- name: DeleteProjectExclusions :exec
DELETE FROM project_excluded_containers
WHERE project_id = ?
`

func (q *Queries) DeleteProjectExclusions(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectExclusions, projectID)
	return err
}

const deleteProjectNodelets = `-- name: DeleteProjectNodelets :exec
DELETE FROM project_nodelets
WHERE project_id = ?
`

func (q *Queries) DeleteProjectNodelets(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectNodelets, projectID)
	return err
}

const getAgentSettings = `-- name: GetAgentSettings :one
SELECT id, max_turns, updated_at FROM agent_settings WHERE id = 'default'
`

func (q *Queries) GetAgentSettings(ctx context.Context) (AgentSetting, error) {
	row := q.db.QueryRowContext(ctx, getAgentSettings)
	var i AgentSetting
	err := row.Scan(&i.ID, &i.MaxTurns, &i.UpdatedAt)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, github_repo, created_at, updated_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.GithubRepo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, name, password FROM users LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(&i.Username, &i.Name, &i.Password)
	return i, err
}

const insertDSNEntry = `-- name: InsertDSNEntry :exec
INSERT INTO container_dsn_entries (nodelet_id, container_id, key, value)
VALUES (?, ?, ?, ?)
`

type InsertDSNEntryParams struct {
	NodeletID   string `json:"nodelet_id"`
	ContainerID string `json:"container_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

func (q *Queries) InsertDSNEntry(ctx context.Context, arg InsertDSNEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertDSNEntry,
		arg.NodeletID,
		arg.ContainerID,
		arg.Key,
		arg.Value,
	)
	return err
}

const insertMCPConnection = `-- name: InsertMCPConnection :exec
INSERT INTO mcp_connections (
  id,
  name,
  type,
  transport,
  command,
  args_json,
  env_json,
  url,
  enabled,
  container_id,
  nodelet_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMCPConnectionParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Transport   string `json:"transport"`
	Command     string `json:"command"`
	ArgsJson    string `json:"args_json"`
	EnvJson     string `json:"env_json"`
	Url         string `json:"url"`
	Enabled     int64  `json:"enabled"`
	ContainerID string `json:"container_id"`
	NodeletID   string `json:"nodelet_id"`
}

func (q *Queries) InsertMCPConnection(ctx context.Context, arg InsertMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, insertMCPConnection,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Transport,
		arg.Command,
		arg.ArgsJson,
		arg.EnvJson,
		arg.Url,
		arg.Enabled,
		arg.ContainerID,
		arg.NodeletID,
	)
	return err
}

const insertNodelet = `-- name: InsertNodelet :exec
INSERT INTO nodelets (id, name, address, token)
VALUES (?, ?, ?, ?)
`

type InsertNodeletParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	Token   string `json:"token"`
}

func (q *Queries) InsertNodelet(ctx context.Context, arg InsertNodeletParams) error {
	_, err := q.db.ExecContext(ctx, insertNodelet,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Token,
	)
	return err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects (id, name, description, github_repo, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertProjectParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	GithubRepo  string `json:"github_repo"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.GithubRepo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertProjectExclusion = `-- name: InsertProjectExclusion :exec
INSERT INTO project_excluded_containers (project_id, ref)
VALUES (?, ?)
`

type InsertProjectExclusionParams struct {
	ProjectID string `json:"project_id"`
	Ref       string `json:"ref"`
}

func (q *Queries) InsertProjectExclusion(ctx context.Context, arg InsertProjectExclusionParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectExclusion, arg.ProjectID, arg.Ref)
	return err
}

const insertProjectNodelet = `-- name: InsertProjectNodelet :exec
INSERT INTO project_nodelets (project_id, nodelet_id, position)
VALUES (?, ?, ?)
`

type InsertProjectNodeletParams struct {
	ProjectID string `json:"project_id"`
	NodeletID string `json:"nodelet_id"`
	Position  int64  `json:"position"`
}

func (q *Queries) InsertProjectNodelet(ctx context.Context, arg InsertProjectNodeletParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectNodelet, arg.ProjectID, arg.NodeletID, arg.Position)
	return err
}

const listDSNEntries = `-- name: ListDSNEntries :many
SELECT nodelet_id, container_id, key, value
FROM container_dsn_entries
ORDER BY nodelet_id, container_id, key
`

func (q *Queries) ListDSNEntries(ctx context.Context) ([]ContainerDsnEntry, error) {
	rows, err := q.db.QueryContext(ctx, listDSNEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContainerDsnEntry
	for rows.Next() {
		var i ContainerDsnEntry
		if err := rows.Scan(
			&i.NodeletID,
			&i.ContainerID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDSNEntriesForContainer = `-- name: ListDSNEntriesForContainer :many
SELECT nodelet_id, container_id, key, value
FROM container_dsn_entries
WHERE nodelet_id = ? AND container_id = ?
ORDER BY key
`

type ListDSNEntriesForContainerParams struct {
	NodeletID   string `json:"nodelet_id"`
	ContainerID string `json:"container_id"`
}

func (q *Queries) ListDSNEntriesForContainer(ctx context.Context, arg ListDSNEntriesForContainerParams) ([]ContainerDsnEntry, error) {
	rows, err := q.db.QueryContext(ctx, listDSNEntriesForContainer, arg.NodeletID, arg.ContainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContainerDsnEntry
	for rows.Next() {
		var i ContainerDsnEntry
		if err := rows.Scan(
			&i.NodeletID,
			&i.ContainerID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPConnections = `-- name: ListMCPConnections :many
SELECT
  id,
  name,
  type,
  transport,
  command,
  args_json,
  env_json,
  url,
  enabled,
  container_id,
  nodelet_id
FROM mcp_connections
ORDER BY rowid
`

func (q *Queries) ListMCPConnections(ctx context.Context) ([]McpConnection, error) {
	rows, err := q.db.QueryContext(ctx, listMCPConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpConnection
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Transport,
			&i.Command,
			&i.ArgsJson,
			&i.EnvJson,
			&i.Url,
			&i.Enabled,
			&i.ContainerID,
			&i.NodeletID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodelets = `-- name: ListNodelets :many
SELECT id, name, address, token FROM nodelets ORDER BY rowid
`

func (q *Queries) ListNodelets(ctx context.Context) ([]Nodelet, error) {
	rows, err := q.db.QueryContext(ctx, listNodelets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nodelet
	for rows.Next() {
		var i Nodelet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectExclusions = `-- name: ListProjectExclusions :many
SELECT project_id, ref
FROM project_excluded_containers
ORDER BY project_id, ref
`

func (q *Queries) ListProjectExclusions(ctx context.Context) ([]ProjectExcludedContainer, error) {
	rows, err := q.db.QueryContext(ctx, listProjectExclusions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectExcludedContainer
	for rows.Next() {
		var i ProjectExcludedContainer
		if err := rows.Scan(&i.ProjectID, &i.Ref); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectExclusionsForProject = `-- name: ListProjectExclusionsForProject :many
SELECT project_id, ref
FROM project_excluded_containers
WHERE project_id = ?
ORDER BY ref
`

func (q *Queries) ListProjectExclusionsForProject(ctx context.Context, projectID string) ([]ProjectExcludedContainer, error) {
	rows, err := q.db.QueryContext(ctx, listProjectExclusionsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectExcludedContainer
	for rows.Next() {
		var i ProjectExcludedContainer
		if err := rows.Scan(&i.ProjectID, &i.Ref); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNodelets = `-- name: ListProjectNodelets :many
SELECT project_id, nodelet_id, position
FROM project_nodelets
ORDER BY project_id, position, nodelet_id
`

func (q *Queries) ListProjectNodelets(ctx context.Context) ([]ProjectNodelet, error) {
	rows, err := q.db.QueryContext(ctx, listProjectNodelets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectNodelet
	for rows.Next() {
		var i ProjectNodelet
		if err := rows.Scan(&i.ProjectID, &i.NodeletID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNodeletsForProject = `-- name: ListProjectNodeletsForProject :many
SELECT project_id, nodelet_id, position
FROM project_nodelets
WHERE project_id = ?
ORDER BY position, nodelet_id
`

func (q *Queries) ListProjectNodeletsForProject(ctx context.Context, projectID string) ([]ProjectNodelet, error) {
	rows, err := q.db.QueryContext(ctx, listProjectNodeletsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectNodelet
	for rows.Next() {
		var i ProjectNodelet
		if err := rows.Scan(&i.ProjectID, &i.NodeletID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, github_repo, created_at, updated_at
FROM projects
ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GithubRepo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectExclusion = `-- name: RemoveProjectExclusion :execrows
DELETE FROM project_excluded_containers
WHERE project_id = ?1 AND ref = ?2
`

type RemoveProjectExclusionParams struct {
	ProjectID string `json:"project_id"`
	Ref       string `json:"ref"`
}

func (q *Queries) RemoveProjectExclusion(ctx context.Context, arg RemoveProjectExclusionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeProjectExclusion, arg.ProjectID, arg.Ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeProjectNodelet = `-- name: RemoveProjectNodelet :execrows
DELETE FROM project_nodelets
WHERE project_id = ?1 AND nodelet_id = ?2
`

type RemoveProjectNodeletParams struct {
	ProjectID string `json:"project_id"`
	NodeletID string `json:"nodelet_id"`
}

func (q *Queries) RemoveProjectNodelet(ctx context.Context, arg RemoveProjectNodeletParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeProjectNodelet, arg.ProjectID, arg.NodeletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchProject = `-- name: TouchProject :execrows
UPDATE projects
SET updated_at = ?1
WHERE id = ?2
`

type TouchProjectParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchProject(ctx context.Context, arg TouchProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchProject, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects
SET name = ?, description = ?, github_repo = ?, updated_at = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	GithubRepo  string `json:"github_repo"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.GithubRepo,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAgentSettings = `-- name: UpsertAgentSettings :exec
INSERT INTO agent_settings (id, max_turns, updated_at)
VALUES ('default', ?, ?)
ON CONFLICT(id) DO UPDATE SET
  max_turns = excluded.max_turns,
  updated_at = excluded.updated_at
`

type UpsertAgentSettingsParams struct {
	MaxTurns  int64 `json:"max_turns"`
	UpdatedAt int64 `json:"updated_at"`
}

func (q *Queries) UpsertAgentSettings(ctx context.Context, arg UpsertAgentSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentSettings, arg.MaxTurns, arg.UpdatedAt)
	return err
}

const upsertDSNEntry = `-- name: UpsertDSNEntry :exec
INSERT INTO container_dsn_entries (nodelet_id, container_id, key, value)
VALUES (?, ?, ?, ?)
ON CONFLICT(nodelet_id, container_id, key) DO UPDATE SET value = excluded.value
`

type UpsertDSNEntryParams struct {
	NodeletID   string `json:"nodelet_id"`
	ContainerID string `json:"container_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
}

func (q *Queries) UpsertDSNEntry(ctx context.Context, arg UpsertDSNEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertDSNEntry,
		arg.NodeletID,
		arg.ContainerID,
		arg.Key,
		arg.Value,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (username, name, password) VALUES (?, ?, ?)
ON CONFLICT(username) DO UPDATE SET name = excluded.name, password = excluded.password
`

type UpsertUserParams struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.Username, arg.Name, arg.Password)
	return err
}
