package workspace

import "encoding/json"

var (
	readSchema  = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"path":{"type":"string","description":"Path to the file to read, relative to the workspace or absolute inside it."},"offset":{"type":"integer","minimum":1,"description":"Optional 1-indexed line number to start reading from."},"limit":{"type":"integer","minimum":1,"description":"Optional maximum number of lines to read."}},"required":["path"]}`)
	lsSchema    = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"path":{"type":"string","description":"Directory path to list, relative to the workspace or absolute inside it."}},"required":["path"]}`)
	grepSchema  = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"pattern":{"type":"string","description":"Regular expression to search for."},"path":{"type":"string","description":"File or directory path to search. Defaults to the workspace root."},"include":{"type":"string","description":"Optional glob matched against relative paths or file names."},"maxResults":{"type":"integer","minimum":1,"description":"Maximum number of matching lines to return."}},"required":["pattern"]}`)
	findSchema  = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"path":{"type":"string","description":"Directory path to search. Defaults to the workspace root."},"pattern":{"type":"string","description":"Name substring or glob pattern. Empty returns the first entries."},"type":{"type":"string","enum":["any","file","dir"],"description":"Path type filter."},"maxResults":{"type":"integer","minimum":1,"description":"Maximum number of paths to return."}}}`)
	bashSchema  = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"command":{"type":"string","description":"Shell command to run."},"cwd":{"type":"string","description":"Working directory inside the workspace. Defaults to the workspace root."},"timeoutMs":{"type":"integer","minimum":1,"description":"Optional timeout in milliseconds, capped by runtime policy."}},"required":["command"]}`)
	writeSchema = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"path":{"type":"string","description":"File path to create or write, relative to the workspace or absolute inside it."},"content":{"type":"string","description":"Content to write."},"append":{"type":"boolean","description":"Append to the file instead of replacing it."}},"required":["path","content"]}`)
	editSchema  = json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"path":{"type":"string","description":"File path to edit, relative to the workspace or absolute inside it."},"oldText":{"type":"string","description":"Exact text to replace. It must appear in the file."},"newText":{"type":"string","description":"Replacement text."},"replaceAll":{"type":"boolean","description":"Replace every occurrence instead of requiring exactly one occurrence."}},"required":["path","oldText","newText"]}`)
)
